### ISSUE TITLE
Usage of Cache

### ISSUE THREAD

**Issue by lukasniemeier** [zalando/cassandra-etcd-seed-provider#2]
Is there a reason why this provider is using a cache? Are there multiple calls in a short time span expected? Does *Cassandra* expect this call to be fast on successive executions?

I'm just wondering if we can get rid of this added dependency, since we should expose the most current state of Etcd whenever *Cassandra* decides to ask for it.

**Comment by lmineiro** [comment]
Sorry for the late reply. Yes, the cache is in place for any burst of calls that may happen. It's only 5sec to make sure that no multiple topology changes could happen during this short period.

As for the dependency, if you meant Guava, it's already in the classpath.
